### ISSUE TITLE
IRB Tab not using monospaced typeface

### ISSUE THREAD

**Issue by gadtfly** [ruboto/ruboto-irb#29]
For the love of all that is programming, [proportional fonts are not appropriate in this context](https://en.wikipedia.org/wiki/Monospaced_font#Use_in_computers).

If for nothing else, then for consistency with editor tab,  [which is already monospaced](https://github.com/ruboto/ruboto-irb/blob/master/res/layout/main.xml#L57).

If you don't know what I'm talking about, compare:

----

----
........
mmrnmmmm

----
```
........
mmrnmmmm
```

**Comment by donv** [comment]
Hi @gadtfly !

Monospaced font seems like a good idea.

Seems like @rscottm is a bit busy at the time.  Would you care to take a stab at it?
